//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fluit.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fluit.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of holes pressed:.
        /// </summary>
        public static string AmountHoles {
            get {
                return ResourceManager.GetString("AmountHoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to make us happy? Buy the app now!.
        /// </summary>
        public static string BuyApp {
            get {
                return ResourceManager.GetString("BuyApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Flute Instrument.
        /// </summary>
        public static string BuyAppButton {
            get {
                return ResourceManager.GetString("BuyAppButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have suggestions, questions, comments or if you are in desperate need of technical support, please contact us at JensDennisBV@gmail.com..
        /// </summary>
        public static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like you normaly would.
        /// </summary>
        public static string HelpBottom {
            get {
                return ResourceManager.GetString("HelpBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the flute,.
        /// </summary>
        public static string HelpTop {
            get {
                return ResourceManager.GetString("HelpTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing.
        /// </summary>
        public static string IsPlaying {
            get {
                return ResourceManager.GetString("IsPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string IsSilent {
            get {
                return ResourceManager.GetString("IsSilent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred the last time that the application run. Would you like to send an (automatic generated) email to report the error?.
        /// </summary>
        public static string LittleWatsonSendMail {
            get {
                return ResourceManager.GetString("LittleWatsonSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occured. Would you like to send an (automatic generated) email to report the error?.
        /// </summary>
        public static string LittleWatsonUnexpectedError {
            get {
                return ResourceManager.GetString("LittleWatsonUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to review Flute Instrument?.
        /// </summary>
        public static string RateApplication {
            get {
                return ResourceManager.GetString("RateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you like this app then please write a short review in the marketplace..
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of trial, please click Ok to buy the app in the marketplace..
        /// </summary>
        public static string TrialEnded {
            get {
                return ResourceManager.GetString("TrialEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds to make to end trial:.
        /// </summary>
        public static string TrialMax {
            get {
                return ResourceManager.GetString("TrialMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
